using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HydroTaskpane2.References
{
    public enum AttributeClass_e
    {
        // Standard
        NONE,
        description,
        adddescription,
        addtext,
        caddescription,
        materialhydro1,
        materialhydro2,
        materialhydroadd,
        materialoriginal,
        materialoriginaladd,
        heattreatment,
        preconditioning,
        surfacefinish,
        standardcolor,
        lacquering,
        addinformation,
        basedon,
        generaltolerances,
        sepmethodsprecision,
        semifinishedstandard,
        weldment,
        dyepenetrationinsp,
        visualinsp,
        qualitylevelimp,
        measurements,
        measurements_inch,
        weight_kg,
        weight_lbs,
        weldassembly,
        components,
        changeno,
        changeshortdescription,
        occurs,
        drafter,
        date,
        material,
        specialselection,
        yieldstrength,
        tensilestrength,
        elongation,
        // Angebotsbläatter
        revisionstatus,
        capacity_t,
        capacity_ton,
        capacity_lbs,
        capacity_kg,
        capacity_KN,
        ac,
        typeofengine,
        closedheight_mm,
        closedheight_inch,
        closedheightA_mm,
        closedheightA_inch,
        liftstrokeB_mm,
        liftstrokeB_inch,
        closedheightC_mm,
        closedheightC_inch,
        liftstrokeD_mm,
        liftstrokeD_inch,
        Model,
        hydrauliclift_mm,
        hydrauliclift_inch,
        screwextension_mm,
        screwextension_inch,
        extendedheight_mm,
        extendedheight_inch,
        usableheight_mm,
        usableheight_inch
    }
}
